_manifest:
  urn: "urn:knowledge:koda:tools:routing:1.0.0"
  federation:
    visibility: internal
    license: "Proprietary"
  compatibility:
    min_consumer_version: "1.0.0"
    breaking_changes_from: null
  resolution:
    canonical_url: "file://knowledge/domains/moltbot/docs/concepts/kb_routing.yaml"
    mirrors: []
  provenance:
    created_by: "Moltbot Docs"
    created_at: "2026-01-29"
    last_modified_by: "Codex"
    last_modified_at: "2026-01-29"
    signature: null

ID: MOLTBOT-KB-CONCEPTS-ROUTING-01
Version: 1.0.0
Status: Draft
Human-Creator: Moltbot Docs
Human-Editor: Codex
Model-Collaborator: OpenAI-Codex
Creation-Date: '2026-01-29'
Modification-Date: '2026-01-29'
Ctx: 'Moltbot concepts: routing'
LLM_Parsing_Instructions:
  ID: KODA-LLM-PARSER-01
  Req: Mandatory block following Metadata.
  Prohib: Using for artifact creation or translation.
  Content: |-
    BEGIN_LLM_INSTRUCTIONS
    You are an AI agent consuming a KODA artifact. Parse with absolute fidelity.

    FIDELITY: Preserve meat (essential information) and skeleton (structure: headers, IDs, lists, tables) with zero loss. Ignore fat (filler words, rhetoric, stylistic prose).

    LEXICON (expand before processing): Act->Action, Cond->Condition, Ctx->Context, Ctx_Required->Required External Reference, Ctx_Optional->Optional External Reference, Def->Definition, Ex->Example, Mssn->Mission, Obj->Objective, Proc->Process, Purp->Purpose, Ref->Reference, XRef->Cross-Artifact Reference, XRef_Required->Mandatory Cross-Artifact Reference, Req->Requirement, Res->Result, Src->Source, Prohib->Prohibition, Warn->Warning, Just->Justification, Rec->Recommendation

    REFERENCE POLICY: Ref: is internal only—must point to existing ID within THIS document. XRef/XRef_Required: are external only—must point to a URN (optionally with #ID fragment) in another artifact. External documents without specific ID use Ctx:, Ctx_Required:, or Ctx_Optional:.

    LANGUAGE POLICY: Keywords in English, content in original language. Never translate content.
    END_LLM_INSTRUCTIONS
Purp: Routing
Src:
- File: output/concepts/multi-agent.md
- File: output/concepts/channel-routing.md
Sections:
- ID: CONCEPTS-MULTI-AGENT
  Src:
    File: output/concepts/multi-agent.md
    URL: https://docs.molt.bot/concepts/multi-agent
  Facts: |-
    H1: Multi-Agent Routing - Moltbot
    H1: Multi-Agent Routing
    Multi-Agent Routing
    Goal: multiple _isolated_ agents (separate workspace + `agentDir` \+ sessions), plus multiple channel accounts (e.g. two WhatsApps) in one running Gateway. Inbound is routed to an agent via bindings.
    What is "one agent"?
    An **agent** is a fully scoped brain with its own:
    - **Workspace** (files, AGENTS.md/SOUL.md/USER.md, local notes, persona rules).
    - **State directory** (`agentDir`) for auth profiles, model registry, and per-agent config.
    - **Session store** (chat history + routing state) under `~/.clawdbot/agents/<agentId>/sessions`.
    Auth profiles are **per-agent**. Each agent reads from its own:
    Main agent credentials are **not** shared automatically. Never reuse `agentDir` across agents (it causes auth/session collisions). If you want to share creds, copy `auth-profiles.json` into the other agent's `agentDir`. Skills are per-agent via each workspace's `skills/` folder, with shared skills available from `~/.clawdbot/skills`. See [Skills: per-agent vs shared](/tools/skills#per-agent-vs-shared-skills). The Gateway can host **one agent** (default) or **many agents** side-by-side. **Workspace note:** each agent's workspace is the **default cwd** , not a hard sandbox. Relative paths resolve inside the workspace, but absolute paths can reach other host locations unless sandboxing is enabled. See [Sandboxing](/gateway/sandboxing).
    Paths (quick map)
    - Config: `~/.clawdbot/moltbot.json` (or `CLAWDBOT_CONFIG_PATH`)
    - State dir: `~/.clawdbot` (or `CLAWDBOT_STATE_DIR`)
    - Workspace: `~/clawd` (or `~/clawd-<agentId>`)
    - Agent dir: `~/.clawdbot/agents/<agentId>/agent` (or `agents.list[].agentDir`)
    - Sessions: `~/.clawdbot/agents/<agentId>/sessions`
    Single-agent mode (default)
    If you do nothing, Moltbot runs a single agent:
    - `agentId` defaults to **`main`**.
    - Sessions are keyed as `agent:main:<mainKey>`.
    - Workspace defaults to `~/clawd` (or `~/clawd-<profile>` when `CLAWDBOT_PROFILE` is set).
    - State defaults to `~/.clawdbot/agents/main/agent`.
    Agent helper
    Use the agent wizard to add a new isolated agent:
    Then add `bindings` (or let the wizard do it) to route inbound messages. Verify with:
    Multiple agents = multiple people, multiple personalities
    With **multiple agents** , each `agentId` becomes a **fully isolated persona** :
    - **Different phone numbers/accounts** (per channel `accountId`).
    - **Different personalities** (per-agent workspace files like `AGENTS.md` and `SOUL.md`).
    - **Separate auth + sessions** (no cross-talk unless explicitly enabled).
    This lets **multiple people** share one Gateway server while keeping their AI "brains" and data isolated.
    One WhatsApp number, multiple people (DM split)
    You can route **different WhatsApp DMs** to different agents while staying on **one WhatsApp account**. Match on sender E.164 (like `+15551234567`) with `peer.kind: "dm"`. Replies still come from the same WhatsApp number (no peragent sender identity). Important detail: direct chats collapse to the agent's **main session key** , so true isolation requires **one agent per person**. Example:
    Notes:
    - DM access control is **global per WhatsApp account** (pairing/allowlist), not per agent.
    - For shared groups, bind the group to one agent or use [Broadcast groups](/broadcast-groups).
    Routing rules (how messages pick an agent)
    Bindings are **deterministic** and **most-specific wins** :
    - `peer` match (exact DM/group/channel id)
    - `guildId` (Discord)
    - `teamId` (Slack)
    - `accountId` match for a channel
    - channel-level match (`accountId: "*"`)
    - fallback to default agent (`agents.list[].default`, else first list entry, default: `main`)
    Multiple accounts / phone numbers
    Channels that support **multiple accounts** (e.g. WhatsApp) use `accountId` to identify each login. Each `accountId` can be routed to a different agent, so one server can host multiple phone numbers without mixing sessions.
    Concepts
    - `agentId`: one "brain" (workspace, per-agent auth, per-agent session store).
    - `accountId`: one channel account instance (e.g. WhatsApp account `"personal"` vs `"biz"`).
    - `binding`: routes inbound messages to an `agentId` by `(channel, accountId, peer)` and optionally guild/team ids.
    - Direct chats collapse to `agent:<agentId>:<mainKey>` (per-agent "main"; `session.mainKey`).
    Example: two WhatsApps -> two agents
    `~/.clawdbot/moltbot.json` (JSON5):
    Example: WhatsApp daily chat + Telegram deep work
    Split by channel: route WhatsApp to a fast everyday agent and Telegram to an Opus agent.
    Notes:
    - If you have multiple accounts for a channel, add `accountId` to the binding (for example `{ channel: "whatsapp", accountId: "personal" }`).
    - To route a single DM/group to Opus while keeping the rest on chat, add a `match.peer` binding for that peer; peer matches always win over channel-wide rules.
    Example: same channel, one peer to Opus
    Keep WhatsApp on the fast agent, but route one DM to Opus:
    Peer bindings always win, so keep them above the channel-wide rule.
    Family agent bound to a WhatsApp group
    Bind a dedicated family agent to a single WhatsApp group, with mention gating and a tighter tool policy:
    Notes:
    - Tool allow/deny lists are **tools** , not skills. If a skill needs to run a binary, ensure `exec` is allowed and the binary exists in the sandbox.
    - For stricter gating, set `agents.list[].groupChat.mentionPatterns` and keep group allowlists enabled for the channel.
    Per-Agent Sandbox and Tool Configuration
    Starting with v2026.1.6, each agent can have its own sandbox and tool restrictions:
    Note: `setupCommand` lives under `sandbox.docker` and runs once on container creation. Per-agent `sandbox.docker.*` overrides are ignored when the resolved scope is `"shared"`. **Benefits:**
    - **Security isolation** : Restrict tools for untrusted agents
    - **Resource control** : Sandbox specific agents while keeping others on host
    - **Flexible policies** : Different permissions per agent
    Note: `tools.elevated` is **global** and sender-based; it is not configurable per agent. If you need per-agent boundaries, use `agents.list[].tools` to deny `exec`. For group targeting, use `agents.list[].groupChat.mentionPatterns` so @mentions map cleanly to the intended agent. See [Multi-Agent Sandbox & Tools](/multi-agent-sandbox-tools) for detailed examples.
  Ex:
  - ID: EX-CONCEPTS-MULTI-AGENT-FF5585D6FB
    Ctx: Copy
    Body: ~/.clawdbot/agents/<agentId>/agent/auth-profiles.json
  - ID: EX-CONCEPTS-MULTI-AGENT-A4807E6568
    Ctx: Copy
    Body: moltbot agents add work
  - ID: EX-CONCEPTS-MULTI-AGENT-B721D06BDD
    Ctx: Copy
    Body: moltbot agents list --bindings
  - ID: EX-CONCEPTS-MULTI-AGENT-C6F7B3C009
    Ctx: Copy
    Body: |-
      {
      agents: {
      list: [
      { id: "alex", workspace: "~/clawd-alex" },
      { id: "mia", workspace: "~/clawd-mia" }
      ]
      },
      bindings: [
      { agentId: "alex", match: { channel: "whatsapp", peer: { kind: "dm", id: "+15551230001" } } },
      { agentId: "mia",  match: { channel: "whatsapp", peer: { kind: "dm", id: "+15551230002" } } }
      ],
      channels: {
      whatsapp: {
      dmPolicy: "allowlist",
      allowFrom: ["+15551230001", "+15551230002"]
      }
      }
      }
  - ID: EX-CONCEPTS-MULTI-AGENT-7B9F6C1D1B
    Ctx: Copy
    Body: |-
      {
      agents: {
      list: [
      {
      id: "home",
      default: true,
      name: "Home",
      workspace: "~/clawd-home",
      agentDir: "~/.clawdbot/agents/home/agent",
      },
      {
      id: "work",
      name: "Work",
      workspace: "~/clawd-work",
      agentDir: "~/.clawdbot/agents/work/agent",
      },
      ],
      },
  - ID: EX-CONCEPTS-MULTI-AGENT-B1406342DC
    Body: |-
      // Deterministic routing: first match wins (most-specific first).
      bindings: [
      { agentId: "home", match: { channel: "whatsapp", accountId: "personal" } },
      { agentId: "work", match: { channel: "whatsapp", accountId: "biz" } },
  - ID: EX-CONCEPTS-MULTI-AGENT-3B942A1470
    Body: |-
      // Optional per-peer override (example: send a specific group to work agent).
      {
      agentId: "work",
      match: {
      channel: "whatsapp",
      accountId: "personal",
      peer: { kind: "group", id: "[[email protected]](/cdn-cgi/l/email-protection)" },
      },
      },
      ],
  - ID: EX-CONCEPTS-MULTI-AGENT-E32A6EF033
    Body: |-
      // Off by default: agent-to-agent messaging must be explicitly enabled + allowlisted.
      tools: {
      agentToAgent: {
      enabled: false,
      allow: ["home", "work"],
      },
      },
  - ID: EX-CONCEPTS-MULTI-AGENT-0E8CC3ACEE
    Body: |-
      channels: {
      whatsapp: {
      accounts: {
      personal: {
      // Optional override. Default: ~/.clawdbot/credentials/whatsapp/personal
      // authDir: "~/.clawdbot/credentials/whatsapp/personal",
      },
      biz: {
      // Optional override. Default: ~/.clawdbot/credentials/whatsapp/biz
      // authDir: "~/.clawdbot/credentials/whatsapp/biz",
      },
      },
      },
      },
      }
  - ID: EX-CONCEPTS-MULTI-AGENT-AB2277619D
    Ctx: Copy
    Body: |-
      {
      agents: {
      list: [
      {
      id: "chat",
      name: "Everyday",
      workspace: "~/clawd-chat",
      model: "anthropic/claude-sonnet-4-5"
      },
      {
      id: "opus",
      name: "Deep Work",
      workspace: "~/clawd-opus",
      model: "anthropic/claude-opus-4-5"
      }
      ]
      },
      bindings: [
      { agentId: "chat", match: { channel: "whatsapp" } },
      { agentId: "opus", match: { channel: "telegram" } }
      ]
      }
  - ID: EX-CONCEPTS-MULTI-AGENT-E16D250926
    Ctx: Copy
    Body: |-
      {
      agents: {
      list: [
      { id: "chat", name: "Everyday", workspace: "~/clawd-chat", model: "anthropic/claude-sonnet-4-5" },
      { id: "opus", name: "Deep Work", workspace: "~/clawd-opus", model: "anthropic/claude-opus-4-5" }
      ]
      },
      bindings: [
      { agentId: "opus", match: { channel: "whatsapp", peer: { kind: "dm", id: "+15551234567" } } },
      { agentId: "chat", match: { channel: "whatsapp" } }
      ]
      }
  - ID: EX-CONCEPTS-MULTI-AGENT-F722C54FC2
    Ctx: Copy
    Body: |-
      {
      agents: {
      list: [
      {
      id: "family",
      name: "Family",
      workspace: "~/clawd-family",
      identity: { name: "Family Bot" },
      groupChat: {
      mentionPatterns: ["@family", "@familybot", "@Family Bot"]
      },
      sandbox: {
      mode: "all",
      scope: "agent"
      },
      tools: {
      allow: ["exec", "read", "sessions_list", "sessions_history", "sessions_send", "sessions_spawn", "session_status"],
      deny: ["write", "edit", "apply_patch", "browser", "canvas", "nodes", "cron"]
      }
      }
      ]
      },
      bindings: [
      {
      agentId: "family",
      match: {
      channel: "whatsapp",
      peer: { kind: "group", id: "[[email protected]](/cdn-cgi/l/email-protection)" }
      }
      }
      ]
      }
  - ID: EX-CONCEPTS-MULTI-AGENT-622DC99686
    Ctx: Copy
    Body: |-
      {
      agents: {
      list: [
      {
      id: "personal",
      workspace: "~/clawd-personal",
      sandbox: {
      mode: "off",  // No sandbox for personal agent
      },
      // No tool restrictions - all tools available
      },
      {
      id: "family",
      workspace: "~/clawd-family",
      sandbox: {
      mode: "all",     // Always sandboxed
      scope: "agent",  // One container per agent
      docker: {
      // Optional one-time setup after container creation
      setupCommand: "apt-get update && apt-get install -y git curl",
      },
      },
      tools: {
      allow: ["read"],                    // Only read tool
      deny: ["exec", "write", "edit", "apply_patch"],    // Deny others
      },
      },
      ],
      },
      }
- ID: CONCEPTS-CHANNEL-ROUTING
  Src:
    File: output/concepts/channel-routing.md
    URL: https://docs.molt.bot/concepts/channel-routing
  Facts: |-
    H1: Channel routing - Moltbot
    H1: Channel routing
    Channels & routing
    Moltbot routes replies **back to the channel where a message came from**. The model does not choose a channel; routing is deterministic and controlled by the host configuration.
    Key terms
    - **Channel** : `whatsapp`, `telegram`, `discord`, `slack`, `signal`, `imessage`, `webchat`.
    - **AccountId** : perchannel account instance (when supported).
    - **AgentId** : an isolated workspace + session store ("brain").
    - **SessionKey** : the bucket key used to store context and control concurrency.
    Session key shapes (examples)
    Direct messages collapse to the agent's **main** session:
    - `agent:<agentId>:<mainKey>` (default: `agent:main:main`)
    Groups and channels remain isolated per channel:
    - Groups: `agent:<agentId>:<channel>:group:<id>`
    - Channels/rooms: `agent:<agentId>:<channel>:channel:<id>`
    Threads:
    - Slack/Discord threads append `:thread:<threadId>` to the base key.
    - Telegram forum topics embed `:topic:<topicId>` in the group key.
    Examples:
    - `agent:main:telegram:group:-1001234567890:topic:42`
    - `agent:main:discord:channel:123456:thread:987654`
    Routing rules (how an agent is chosen)
    Routing picks **one agent** for each inbound message:
    - **Exact peer match** (`bindings` with `peer.kind` \+ `peer.id`).
    - **Guild match** (Discord) via `guildId`.
    - **Team match** (Slack) via `teamId`.
    - **Account match** (`accountId` on the channel).
    - **Channel match** (any account on that channel).
    - **Default agent** (`agents.list[].default`, else first list entry, fallback to `main`).
    The matched agent determines which workspace and session store are used.
    Broadcast groups (run multiple agents)
    Broadcast groups let you run **multiple agents** for the same peer **when Moltbot would normally reply** (for example: in WhatsApp groups, after mention/activation gating). Config:
    See: [Broadcast Groups](/broadcast-groups).
    Config overview
    - `agents.list`: named agent definitions (workspace, model, etc.).
    - `bindings`: map inbound channels/accounts/peers to agents.
    Example:
    Session storage
    Session stores live under the state directory (default `~/.clawdbot`):
    - `~/.clawdbot/agents/<agentId>/sessions/sessions.json`
    - JSONL transcripts live alongside the store
    You can override the store path via `session.store` and `{agentId}` templating.
    WebChat behavior
    WebChat attaches to the **selected agent** and defaults to the agent's main session. Because of this, WebChat lets you see crosschannel context for that agent in one place.
    Reply context
    Inbound replies include:
    - `ReplyToId`, `ReplyToBody`, and `ReplyToSender` when available.
    - Quoted context is appended to `Body` as a `[Replying to ...]` block.
    This is consistent across channels.
  Ex:
  - ID: EX-CONCEPTS-CHANNEL-ROUTING-5D6CCFF84C
    Ctx: Copy
    Body: |-
      {
      broadcast: {
      strategy: "parallel",
      "[[email protected]](/cdn-cgi/l/email-protection)": ["alfred", "baerbel"],
      "+15555550123": ["support", "logger"]
      }
      }
  - ID: EX-CONCEPTS-CHANNEL-ROUTING-E58D363EF1
    Ctx: Copy
    Body: |-
      {
      agents: {
      list: [
      { id: "support", name: "Support", workspace: "~/clawd-support" }
      ]
      },
      bindings: [
      { match: { channel: "slack", teamId: "T123" }, agentId: "support" },
      { match: { channel: "telegram", peer: { kind: "group", id: "-100123" } }, agentId: "support" }
      ]
      }
